const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "null"
const SESSION_ID = "PRABATH-MD~dnVXQI6Q#NIm8vnuoUooFc68SDDU4YF3P0RkcSDoZANQTzA2rOhk"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
